server.port=8081

spring.application.name=StokYonetim
server.error.include-binding-errors=always
server.error.include-message=always
server.error.include-stacktrace=never

spring.datasource.url=jdbc:postgresql://localhost:5432/stokyonetimdb
spring.datasource.username=stok_admin
spring.datasource.password=95SqPpg47CaEa5o


# ddl-auto icin update create veya create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.jwtExpirationMs = 8640000
api.jwtSecret = FgA46yvp3z2aSAmc8jTzFvOSgbIkWfVg